spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/springjpaquerydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        # sout로 출력(가급적 로그 출력으로)
#        show_sql: true
        format_sql: true

logging.level:
  # log로 출력
  org.hibernate.SQL: debug
  # ? 보이게 하기
  org.hibernate.type: trace